=== KristinaEU/Kristina/UULM/DM_Kristina/target/conf/OwlSpeak/settings.dtd
<!ELEMENT owlSetting (platform,URI,HomePath,plugin,Youpi,YoupiPath,YoupiID,YoupiFriendlyName,MatchAgenda,PrioFactor,LoopDuration,MaxSpeechTimeout,speakRate,ttsCodes,ttsMode,asrCodes,asrMode,deriveQuality,dbLogging,callRecording,maxNBestListEntries,SysCommands?,Files?,Users)>
<!ELEMENT platform (#PCDATA)>
<!ELEMENT URI (#PCDATA)>
<!ELEMENT HomePath (#PCDATA)>
<!ELEMENT plugin (#PCDATA)>
<!ELEMENT Youpi (#PCDATA)>
<!ELEMENT YoupiPath (#PCDATA)>
<!ELEMENT YoupiID (#PCDATA)>
<!ELEMENT YoupiFriendlyName (#PCDATA)>
<!ELEMENT MatchAgenda (#PCDATA)>
<!ELEMENT PrioFactor (#PCDATA)>
<!ELEMENT LoopDuration (#PCDATA)>
<!ELEMENT MaxSpeechTimeout (#PCDATA)>
<!ELEMENT speakRate (#PCDATA)>
<!ELEMENT ttsCodes (tts)*>
<!ELEMENT tts (#PCDATA)>
<!ATTLIST tts
   id    CDATA   #REQUIRED
>
<!ELEMENT ttsMode (#PCDATA)>
<!ELEMENT asrCodes (asr)*>
<!ELEMENT asr (#PCDATA)>
<!ATTLIST asr
   id    CDATA   #REQUIRED
>
<!ELEMENT asrMode (#PCDATA)>
<!ELEMENT deriveQuality (#PCDATA)>
<!ELEMENT dbLogging (#PCDATA)>
<!ELEMENT callRecording (#PCDATA)>
<!ELEMENT maxNBestListEntries (#PCDATA)>
<!ELEMENT SysCommands (Command)*>
<!ELEMENT Command (#PCDATA)>
<!ATTLIST Command
   name    CDATA   #REQUIRED
>
<!ELEMENT Files (ontoFile)*>
<!ELEMENT ontoFile (#PCDATA)>
<!ATTLIST ontoFile
   name    CDATA   #REQUIRED
   path  CDATA   #REQUIRED 
   file    CDATA   #REQUIRED
   HISvariant   CDATA   "0"
   policyVariant   CDATA   "0"
   systemStateVariant   CDATA   "0"
>
<!ELEMENT Users (User)*>
<!ELEMENT User (Useronto*)>
<!ATTLIST User 
	name    	CDATA   #REQUIRED
	docType 	CDATA	#REQUIRED
	grammarType CDATA	#REQUIRED
	sleep		CDATA	#REQUIRED
	AutoSave	CDATA	#REQUIRED
>
<!ELEMENT Useronto (#PCDATA)>
<!ATTLIST Useronto
   name    CDATA   #REQUIRED
   status  CDATA   #REQUIRED
>

=== KristinaEU/Kristina/UULM/DialogueManager/conf/OwlSpeak/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE name SYSTEM "http://localhost:8080/settings.dtd">

<owlSetting>
  <!--The platform that is used to run the SDM [voxeo|tellme] -->
  <platform>voxeo</platform>
  <!--Main URL where the root ontology can be found (0=off,1=on) -->
  <URI>http://localhost:8083/OwlSpeakOnto.owl</URI>
  <!--Home directory-->
  <HomePath>./conf/OwlSpeak/</HomePath>
  <!--plugins-->
  <plugin>3</plugin>
  <!--Youpi UPNP Wrapper switch (0=off,1=on) -->
  <Youpi>0</Youpi>
  <!--Youpi UPNP Wrapper switch (0=off,1=on) -->
  <YoupiPath>./conf/OwlSpeak/device.xml</YoupiPath>
  <!--Youpi ID (long value) -->
  <YoupiID>66612341</YoupiID>
  <!--Youpi UPNP Wrapper switch (0=off,1=on) -->
  <YoupiFriendlyName>SDM Study</YoupiFriendlyName>
  <!-- Used to set the Controller to different Agenda-Priority calculation modes -->
  <MatchAgenda>0</MatchAgenda>
  <!-- Factor used for the dynamic Agenda-Priority calculation -->
  <PrioFactor>10</PrioFactor>
  <!-- Duration of Loop -->
  <LoopDuration>7</LoopDuration>
  <!-- Maxspeechtimeout -->
  <MaxSpeechTimeout>10</MaxSpeechTimeout>
  <!-- Speaking rate -->
  <speakRate>+0%</speakRate>
  <ttsCodes>
    <tts id="1">en-gb</tts>
    <tts id="2">en-us</tts>
    <tts id="3">de-de</tts>
  </ttsCodes>
  <ttsMode>1</ttsMode>
  <asrCodes>
    <asr id="1">en-gb</asr>
    <asr id="2">en-us</asr>
    <asr id="3">de-de</asr>
  </asrCodes>
  <asrMode>1</asrMode>
  <deriveQuality>1</deriveQuality>
  <dbLogging>0</dbLogging>
  <callRecording>0</callRecording>
  <kristina>1</kristina>
  <idaco>0</idaco>
  <demo>1</demo>
  <maxNBestListEntries>3</maxNBestListEntries>
  <SysCommands>
    <Command name="reset" />
    <!--to activate set corresponding Agenda in System.owl to respawn=true/-->
    <!--Command name="reduce" /-->
    <Command name="reloadSettings" />
  </SysCommands>
  
  <!-- select type of HISvariant (systemStateVariant 1):
		0: Semantics
		1: Variables
	-->
	
  <!--  select type of policy variant:
  		0: heuristic policy (default)
  		1: trained policy 
  -->
  
  <!--  select type of system state variant:
  		0: single system state (default)
  		1: distribution over all system states (HIS)
  -->
  <Files>
    <!-- <ontoFile name="system" path="./conf/OwlSpeak/" file="System.owl">The System's main Ontology</ontoFile> -->             <!-- Passende Zeile auskommentieren, wenn Ontologie kaputt -->
	<!-- <ontoFile name="travel" path="./conf/OwlSpeak/JAISE/" file="travel.var.jaise.owl" HISvariant="1" policyVariant="0" systemStateVariant="0">Travel JAISE</ontoFile> -->
	<!-- <ontoFile name="heating" path="./conf/OwlSpeak/JAISE\" file="heating.jaise.owl" HISvariant="1" policyVariant="0" systemStateVariant="0">Heating JAISE</ontoFile> -->
	<!-- <ontoFile name="lgus" path="./conf/OwlSpeak/" file="letsGoUs.owl" HISvariant="1" policyVariant="4" systemStateVariant="1">Lets Go User Simulator</ontoFile> -->
	<!-- <ontoFile name="camRestInfo" path="./conf/OwlSpeak/" file="camRestInfo.owl" HISvariant="1" policyVariant="0" systemStateVariant="0">camRestInfo</ontoFile> -->
  	<ontoFile name="kristina" path="./conf/OwlSpeak/" file="kristina.owl" HISvariant="1" policyVariant="6" systemStateVariant="0">kristina</ontoFile>
  </Files>
  
  <Users>
      <!-- select type of voice document:
		1: VoiceDocument - regular vxml doc
		2: HtmlVoiceDocument - html browsing
		4: HtmlSaltDocument
		5: EnhancedVoiceDocument
		6: VoiceDocumentHIS - HIS implementation with n-best-list etc.
		7: VoiceDocumentPOMDP - slot mechanism with n-best-list etc.
		8: KristinaDocument
		10: User Simulation
	-->
	
	<!-- select type of grammar (docType 1,5,6,7):
		1: Nuance GSL
		2: GrXML
		3: JSGF
		4: JSGF as file
	-->
	
	<User name="user" docType="2" grammarType="3" sleep="0" AutoSave="1">            <!-- Passende Zeile auskommentieren, wenn Ontologie kaputt -->
	  <Useronto status="enabled" name="idaco">Userontology</Useronto>	
	  <!-- <Useronto status="enabled" name="camRestInfo">Userontology</Useronto> --> 
    </User>
	<User name="elisabeth" docType="8" grammarType="3" sleep="0" AutoSave="1">
	  <Useronto status="enabled" name="kristina">Userontology</Useronto>
    </User>
	<User name="hans" docType="8" grammarType="3" sleep="0" AutoSave="1">
	  <Useronto status="enabled" name="kristina">Userontology</Useronto>
    </User>
	<User name="iwona" docType="8" grammarType="3" sleep="0" AutoSave="1">
	  <Useronto status="enabled" name="kristina">Userontology</Useronto>
    </User>
	<User name="maria" docType="8" grammarType="3" sleep="0" AutoSave="1">
	  <Useronto status="enabled" name="kristina">Userontology</Useronto>
    </User>
	<User name="juan" docType="8" grammarType="3" sleep="0" AutoSave="1">
	  <Useronto status="enabled" name="kristina">Userontology</Useronto>
    </User>
	<User name="claudia" docType="8" grammarType="3" sleep="0" AutoSave="1">
	  <Useronto status="enabled" name="kristina">Userontology</Useronto>
    </User>
	<User name="jana" docType="8" grammarType="3" sleep="0" AutoSave="1">
	  <Useronto status="enabled" name="kristina">Userontology</Useronto>
    </User>
	<User name="mustafa" docType="8" grammarType="3" sleep="0" AutoSave="1">
	  <Useronto status="enabled" name="kristina">Userontology</Useronto>
    </User>
	<User name="carmen" docType="8" grammarType="3" sleep="0" AutoSave="1">
	  <Useronto status="enabled" name="kristina">Userontology</Useronto>
    </User>
    <User name="carlos" docType="8" grammarType="3" sleep="0" AutoSave="1">
	  <Useronto status="enabled" name="kristina">Userontology</Useronto>
    </User>
  </Users>
</owlSetting>

=== KristinaEU/Kristina/UULM/DM_Kristina/conf/OwlSpeak/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE name SYSTEM "./conf/OwlSpeak/settings.dtd">

<owlSetting>
  <!--The platform that is used to run the SDM [voxeo|tellme] -->
  <platform>voxeo</platform>
  <!--Main URL where the root ontology can be found (0=off,1=on) -->
  <URI>http://localhost:8080/OwlSpeakOnto.owl</URI>
  <!--Home directory-->
  <HomePath>./conf/OwlSpeak/</HomePath>
  <!--plugins-->
  <plugin>3</plugin>
  <!--Youpi UPNP Wrapper switch (0=off,1=on) -->
  <Youpi>0</Youpi>
  <!--Youpi UPNP Wrapper switch (0=off,1=on) -->
  <YoupiPath>..\dm\owlspeak\device.xml</YoupiPath>
  <!--Youpi ID (long value) -->
  <YoupiID>66612341</YoupiID>
  <!--Youpi UPNP Wrapper switch (0=off,1=on) -->
  <YoupiFriendlyName>SDM Study</YoupiFriendlyName>
  <!-- Used to set the Controller to different Agenda-Priority calculation modes -->
  <MatchAgenda>0</MatchAgenda>
  <!-- Factor used for the dynamic Agenda-Priority calculation -->
  <PrioFactor>10</PrioFactor>
  <!-- Duration of Loop -->
  <LoopDuration>7</LoopDuration>
  <!-- Maxspeechtimeout -->
  <MaxSpeechTimeout>10</MaxSpeechTimeout>
  <!-- Speaking rate -->
  <speakRate>+0%</speakRate>
  <ttsCodes>
    <tts id="1">de-de</tts>
    <tts id="2">en-us</tts>
    <tts id="3">zira</tts>
    <tts id="4">tom</tts>
    <tts id="5">de-de-anna</tts>
    <!--<tts id="6">de-de-stefan</tts>-->
	<tts id="6">de-de-katrin</tts>
  </ttsCodes>
  <ttsMode>1</ttsMode>
  <asrCodes>
    <asr id="1">de-de</asr>
    <asr id="2">en-us</asr>
    <asr id="3">de-de</asr>
  </asrCodes>
  <asrMode>1</asrMode>
  <deriveQuality>1</deriveQuality>
  <dbLogging>0</dbLogging>
  <callRecording>0</callRecording>
  <maxNBestListEntries>3</maxNBestListEntries>
  <SysCommands>
    <Command name="reset" />
    <!--to activate set corresponding Agenda in System.owl to respawn=true/-->
    <!--Command name="reduce" /-->
    <Command name="reloadSettings" />
  </SysCommands>
  
  <!-- select type of HISvariant (systemStateVariant 1):
		0: Semantics
		1: Variables
	-->
	
  <!--  select type of policy variant:
  		0: heuristic policy (default)
  		1: trained policy 
  -->
  
  <!--  select type of system state variant:
  		0: single system state (default)
  		1: distribution over all system states (HIS)
  -->
  <Files>
    <!--<ontoFile name="system" path="C:\OwlSpeak\" file="System.owl">The System's main Ontology</ontoFile>-->
	<!--<ontoFile name="travel" path="C:\OwlSpeak\POMDP\" file="travel.var.jaise.owl" HISvariant="1" policyVariant="0" systemStateVariant="0">Travel JAISE</ontoFile>-->
	<!-- <ontoFile name="heating" path="C:\OwlSpeak\JAISE\" file="heating.jaise.owl" HISvariant="1" policyVariant="0" systemStateVariant="0">Heating JAISE</ontoFile> -->
	<ontoFile name="kristina" path="./conf/OwlSpeak/" file="StandardMoves.owl" HISvariant="0" policyVariant="0" systemStateVariant="0">KristinaTest</ontoFile>
  </Files>
  
  <Users>
      <!-- select type of voice document:
		1: VoiceDocument - regular vxml doc
		2: HtmlVoiceDocument - html browsing
		4: HtmlSaltDocument
		5: EnhancedVoiceDocument
		6: VoiceDocumentHIS - HIS implementation with n-best-list etc.
		7: VoiceDocumentPOMDP - slot mechanism with n-best-list etc.
		8: KristinaDocument
		10: User Simulation
	-->
	
	<!-- select type of grammar (docType 1,5,6,7):
		1: Nuance GSL
		2: GrXML
		3: JSGF
		4: JSGF as file
	-->
	
	<User name="user" docType="8" grammarType="5" sleep="0" AutoSave="1">
	  <!-- <Useronto status="enabled" name="travel">Userontology</Useronto> -->
	  <!-- <Useronto status="enabled" name="heating">Userontology</Useronto> -->
	  <Useronto status="enabled" name="kristina">Userontology</Useronto>
    </User>
	<User name="Elisabeth" docType="8" grammarType="5" sleep="0" AutoSave="1">
	  <!-- <Useronto status="enabled" name="travel">Userontology</Useronto> -->
	  <!-- <Useronto status="enabled" name="heating">Userontology</Useronto> -->
	  <Useronto status="enabled" name="kristina">Userontology</Useronto>
    </User>
	<User name="Eugene" docType="8" grammarType="5" sleep="0" AutoSave="1">
	  <!-- <Useronto status="enabled" name="travel">Userontology</Useronto> -->
	  <!-- <Useronto status="enabled" name="heating">Userontology</Useronto> -->
	  <Useronto status="enabled" name="kristina">Userontology</Useronto>
    </User>
	<User name="George" docType="8" grammarType="5" sleep="0" AutoSave="1">
	  <!-- <Useronto status="enabled" name="travel">Userontology</Useronto> -->
	  <!-- <Useronto status="enabled" name="heating">Userontology</Useronto> -->
	  <Useronto status="enabled" name="kristina">Userontology</Useronto>
    </User>
	<User name="Maria" docType="8" grammarType="5" sleep="0" AutoSave="1">
	  <!-- <Useronto status="enabled" name="travel">Userontology</Useronto> -->
	  <!-- <Useronto status="enabled" name="heating">Userontology</Useronto> -->
	  <Useronto status="enabled" name="kristina">Userontology</Useronto>
    </User>
	<User name="Anna" docType="8" grammarType="5" sleep="0" AutoSave="1">
	  <!-- <Useronto status="enabled" name="travel">Userontology</Useronto> -->
	  <!-- <Useronto status="enabled" name="heating">Userontology</Useronto> -->
	  <Useronto status="enabled" name="kristina">Userontology</Useronto>
    </User>
	
  </Users>
</owlSetting>
